version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - auth
      - users
      - products
      - orders

  auth:
    build: ./services/auth
    ports:
      - "3001:3001"
    env_file: .env

  users:
    build: ./services/users
    ports:
      - "3002:3002"
    env_file: .env

  products:
    build: ./services/products
    ports:
      - "3003:3003"
    env_file: .env

  orders:
    build: ./services/orders
    ports:
      - "3004:3004"
    env_file: .env
