ALTER TABLE orders ADD COLUMN IF NOT EXISTS needs_invoice BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_rfc VARCHAR(13);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_business_name VARCHAR(200);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_email VARCHAR(200);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_cfdi_use VARCHAR(3) DEFAULT 'G03';
