ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_id VARCHAR(8);
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_key VARCHAR(3) DEFAULT 'H87';

ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_zip VARCHAR(5);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_regime VARCHAR(3);
