ALTER TABLE products ADD COLUMN IF NOT EXISTS tech_sheet_url TEXT DEFAULT '';

ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_fiscal_address TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier TEXT DEFAULT '';
